[package]
org = "imms"
name = "client"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true
[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
path = "C:\\Users\\lenovo\\Downloads\\Compressed\\mysql-connector-j-8.0.33\\mysql-connector-j-8.0.33.jar"